In [ ]:
print("start!!!!!!!!!!!")

start!!!!!!!!!!!

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import zscore

In [ ]:
df= pd.read_csv("DATA/DataCoSupplyChainDataset.csv",  encoding="latin-1")

df.shape

(180519, 53)

In [ ]:
df.head(3)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class

In [ ]:
print("Dataset column: ", df.columns.tolist())
print("Data types: ", df.dtypes)
print("Missing values: ", df.isnull().sum())
print("Summary statistics: ", df.describe())

Dataset column:  ['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Image', 'Product Name', 'Product Price', 'Product Status', 'shipping date (DateOrders)', 'Shipping Mode']
Data types:  Type                                 str
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                      str
Late_delivery_risk                 int64
Category Id                        int64
Category Name                        str
Customer City                        str
Customer Country                     str
Customer Email                       str
Customer Fname                       str
Customer Id                        int64
Customer Lname                       str
Customer Password                    str
Customer Segment                     str
Customer State                       str
Customer Street                      str
Customer Zipcode                 float64
Department Id                      int64
Department Name                      str
Latitude                         float64
Longitude                        float64
Market                               str
Order City                           str
Order Country                        str
Order Customer Id                  int64
order date (DateOrders)              str
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                         str
Order State                          str
Order Status                         str
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                        str
Product Name                         str
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)           str
Shipping Mode                        str
dtype: object
Missing values:  Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64
Summary statistics:         Days for shipping (real)  Days for shipment (scheduled)  \
count             180519.000000                  180519.000000
mean                   3.497654                       2.931847
std                    1.623722                       1.374449
min                    0.000000                       0.000000
25%                    2.000000                       2.000000
50%                    3.000000                       4.000000
75%                    5.000000                       4.000000
max                    6.000000                       4.000000

       Benefit per order  Sales per customer  Late_delivery_risk  \
count      180519.000000       180519.000000       180519.000000
mean           21.974989          183.107609            0.548291
std           104.433526          120.043670            0.497664
min         -4274.979980            7.490000            0.000000
25%             7.000000          104.379997            0.000000
50%            31.520000          163.990005            1.000000
75%            64.800003          247.399994            1.000000
max           911.799988         1939.989990            1.000000

         Category Id    Customer Id  Customer Zipcode  Department Id  \
count  180519.000000  180519.000000     180516.000000  180519.000000
mean       31.851451    6691.379495      35921.126914       5.443460
std        15.640064    4162.918106      37542.461122       1.629246
min         2.000000       1.000000        603.000000       2.000000
25%        18.000000    3258.500000        725.000000       4.000000
50%        29.000000    6457.000000      19380.000000       5.000000
75%        45.000000    9779.000000      78207.000000       7.000000
max        76.000000   20757.000000      99205.000000      12.000000

            Latitude  ...  Order Item Quantity          Sales  \
count  180519.000000  ...        180519.000000  180519.000000
mean       29.719955  ...             2.127638     203.772096
std         9.813646  ...             1.453451     132.273077
min       -33.937553  ...             1.000000       9.990000
25%        18.265432  ...             1.000000     119.980003
50%        33.144863  ...             1.000000     199.919998
75%        39.279617  ...             3.000000     299.950012
max        48.781933  ...             5.000000    1999.989990

       Order Item Total  Order Profit Per Order  Order Zipcode  \
count     180519.000000           180519.000000   24840.000000
mean         183.107609               21.974989   55426.132327
std          120.043670              104.433526   31919.279101
min            7.490000            -4274.979980    1040.000000
25%          104.379997                7.000000   23464.000000
50%          163.990005               31.520000   59405.000000
75%          247.399994               64.800003   90008.000000
max         1939.989990              911.799988   99301.000000

       Product Card Id  Product Category Id  Product Description  \
count    180519.000000        180519.000000                  0.0
mean        692.509764            31.851451                  NaN
std         336.446807            15.640064                  NaN
min          19.000000             2.000000                  NaN
25%         403.000000            18.000000                  NaN
50%         627.000000            29.000000                  NaN
75%        1004.000000            45.000000                  NaN
max        1363.000000            76.000000                  NaN

       Product Price  Product Status
count  180519.000000        180519.0
mean      141.232550             0.0
std       139.732492             0.0
min         9.990000             0.0
25%        50.000000             0.0
50%        59.990002             0.0
75%       199.990005             0.0
max      1999.989990             0.0

[8 rows x 29 columns]

In [ ]:
columns = [

    "Shipping Mode",
    "Delivery Status",
    "Late_delivery_risk",
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Order Profit Per Order",
    "Sales",
    "Order Item Discount Rate",
    "Customer Segment",
    "Market",
    "Category Name"
]

dataset = df[columns].copy()

path= "DATA/finalDatas.csv"
dataset.to_csv(path, index=False)

dataset.shape

(180519, 11)

In [ ]:
dataset.head(4)

,Shipping Mode,Delivery Status,Late_delivery_risk,Days for shipping (real),Days for shipment (scheduled),Order Profit Per Order,Sales,Order Item Discount Rate,Customer Segment,Market,Category Name
0,Standard Class,Advance shipping,0,3,4,91.250000,327.75,0.04,Consumer,Pacific Asia,Sporting Goods
1,Standard Class,Late delivery,1,5,4,-249.089996,327.75,0.05,Consumer,Pacific Asia,Sporting Goods
2,Standard Class,Shipping on time,0,4,4,-247.779999,327.75,0.06,Consumer,Pacific Asia,Sporting Goods
3,Standard Class,Advance shipping,0,3,4,22.860001,327.75,0.07,Home Office,Pacific Asia,Sporting Goods

In [ ]:
print("Dataset column: ", dataset.columns.tolist())
print("Data types: ", dataset.dtypes)
print("Missing values: ", dataset.isnull().sum())
print("Summary statistics: ", dataset.describe())

Dataset column:  ['Shipping Mode', 'Delivery Status', 'Late_delivery_risk', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Order Profit Per Order', 'Sales', 'Order Item Discount Rate', 'Customer Segment', 'Market', 'Category Name']
Data types:  Shipping Mode                        str
Delivery Status                      str
Late_delivery_risk                 int64
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Order Profit Per Order           float64
Sales                            float64
Order Item Discount Rate         float64
Customer Segment                     str
Market                               str
Category Name                        str
dtype: object
Missing values:  Shipping Mode                    0
Delivery Status                  0
Late_delivery_risk               0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Order Profit Per Order           0
Sales                            0
Order Item Discount Rate         0
Customer Segment                 0
Market                           0
Category Name                    0
dtype: int64
Summary statistics:         Late_delivery_risk  Days for shipping (real)  \
count       180519.000000             180519.000000
mean             0.548291                  3.497654
std              0.497664                  1.623722
min              0.000000                  0.000000
25%              0.000000                  2.000000
50%              1.000000                  3.000000
75%              1.000000                  5.000000
max              1.000000                  6.000000

       Days for shipment (scheduled)  Order Profit Per Order          Sales  \
count                  180519.000000           180519.000000  180519.000000
mean                        2.931847               21.974989     203.772096
std                         1.374449              104.433526     132.273077
min                         0.000000            -4274.979980       9.990000
25%                         2.000000                7.000000     119.980003
50%                         4.000000               31.520000     199.919998
75%                         4.000000               64.800003     299.950012
max                         4.000000              911.799988    1999.989990

       Order Item Discount Rate
count             180519.000000
mean                   0.101668
std                    0.070415
min                    0.000000
25%                    0.040000
50%                    0.100000
75%                    0.160000
max                    0.250000

DATA CLEANING STEPS: Duplicate datas, outliers

In [ ]:

duplicates = dataset.duplicated().sum()
print("Number of duplicate rows: ", duplicates)

Number of duplicate rows:  6364

In [ ]:
if duplicates > 0:
    dataset = dataset.drop_duplicates()
    print("Duplicate rows removed. New shape: ", dataset.shape)

Duplicate rows removed. New shape:  (174155, 11)

In [ ]:
invalid_dimensions_mask = (dataset['Late_delivery_risk'] <= 0) | (dataset['Days for shipping (real)'] <= 0) | (dataset['Days for shipment (scheduled)'] <= 0) | (dataset['Order Profit Per Order'] <= 0) | (dataset['Sales'] <= 0)| (dataset['Order Item Discount Rate'] <= 0)
invalid_count = invalid_dimensions_mask.sum()
print("Number of rows with invalid dimensions: ", invalid_count)

Number of rows with invalid dimensions:  105367

In [ ]:
if invalid_count > 0:
    dataset = dataset[~invalid_dimensions_mask]
    print("Invalid dimension rows removed. New shape: ", dataset.shape)

Invalid dimension rows removed. New shape:  (68788, 11)

In [ ]:
Cols=['Days for shipping (real)',
    'Days for shipment (scheduled)',
    'Order Profit Per Order',
    'Sales',
    'Order Item Discount Rate']
threshold = 2
for c in Cols:
    z_scores= zscore(dataset[c])
    outliers = np.where(np.abs(z_scores) > threshold) 
    
    print(f"Outliers in {c} : {len(outliers[0])} ")

Outliers in Days for shipping (real) : 0
Outliers in Days for shipment (scheduled) : 0
Outliers in Order Profit Per Order : 2636
Outliers in Sales : 1388
Outliers in Order Item Discount Rate : 4112

In [ ]:

capping= dataset.copy()

z= zscore(dataset['Order Profit Per Order'])
capping['Order Profit Per Order'] = np.where( z > threshold,
                            dataset['Order Profit Per Order'].mean() + threshold * dataset['Order Profit Per Order'].std(),
                            dataset['Order Profit Per Order'])
capping['Order Profit Per Order'] = np.where(z < -threshold,
                            dataset['Order Profit Per Order'].mean() - threshold * dataset['Order Profit Per Order'].std(),
                            capping['Order Profit Per Order'])



z= zscore(dataset['Sales'])
capping['Sales'] = np.where( z > threshold,
                            dataset['Sales'].mean() + threshold * dataset['Sales'].std(),
                            dataset['Sales'])
capping['Sales'] = np.where(z < -threshold,
                            dataset['Sales'].mean() - threshold * dataset['Sales'].std(),
                            capping['Sales'])


z= zscore(dataset['Order Item Discount Rate'])
capping['Order Item Discount Rate'] = np.where( z > threshold,
                            dataset['Order Item Discount Rate'].mean() + threshold * dataset['Order Item Discount Rate'].std(),
                            dataset['Order Item Discount Rate'])
capping['Order Item Discount Rate'] = np.where(z < -threshold,
                            dataset['Order Item Discount Rate'].mean() - threshold * dataset['Order Item Discount Rate'].std(),
                            capping['Order Item Discount Rate'])


print("Original shape  :", dataset.shape)
print("Capped shape    :", capping.shape)

dataset= capping
dataset.shape

Original shape  : (68788, 11)
Capped shape    : (68788, 11)

(68788, 11)

In [ ]:
cols = ['Shipping Mode', 'Delivery Status', 'Customer Segment', 'Market', 'Category Name']
for col in cols:
    unique_vals = dataset[col].unique()
    print(f"\n[{col}]  has   {len(unique_vals)} unique values")
    for val in sorted(unique_vals):
        count = (df[col] == val).sum()
        print(f"  {repr(val):<35}  {count:>6,}")